line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "B", "C90"]
ignore = ["E501", "C901"]

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
